import { Roboto } from 'next/font/google';

import RootProvider from './provider';
import { Header } from '@/components/Header';
import { Nav } from '@/components/Nav/Nav';

import '../styles/styles.scss';

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    style: ['normal', 'italic'],
    subsets: ['cyrillic'],
    display: 'swap',
});

export const metadata = {
    title: 'The Pirate Journal',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${roboto.className} light`}>
            <body>
                <RootProvider>
                    <Header />
                    <Nav />
                    <main>{children}</main>
                    <div id="portal-root" />
                </RootProvider>
            </body>
        </html>
    );
}
